name: CI Pipeline
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Run Linter
        run: npm run lint
        # QUALITY GATE: Fails on lint violations

      - name: Build project
        run: docker build .
        # QUALITY GATE: Fails on build errors

      - name: Run tests
        run: pytest tests/
        # QUALITY GATE: Fails on test failures