name: CI Pipeline
on: [push, pull_request]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ENVIRONMENT SETUP
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # DEPENDENCY CACHING
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}

      # LINTING STAGE
      - name: Run Linter
        run: npm run lint || exit 1
        # QUALITY GATE: Fails on lint violations

      # BUILD STAGE
      - name: Build project
        run: docker build -t my-app .
        # QUALITY GATE: Fails on build errors

      # TEST STAGE
      - name: Run tests
        run: npm test
        # QUALITY GATE: Fails on test failures