name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18] # Specify the Node.js versions to test against
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Enable caching for npm dependencies

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --coverage # Run tests with coverage reporting
        continue-on-error: true # Continue on error to allow artifact upload

      - name: Upload coverage report
        if: success() || failure() # Upload coverage report regardless of test success
        run: |
          mkdir -p coverage
          cp -r coverage/* ./coverage/
        continue-on-error: true

      - name: Upload test results
        if: always() # Always upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./coverage # Adjust this path based on your coverage output location

      - name: Upload logs
        if: always() # Always upload logs for debugging
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ./logs # Adjust this path based on your log output location

      - name: Notify failure
        if: failure() # Notify if the tests fail
        run: echo "Tests failed. Please check the logs and coverage reports."